version: '3'

services:
  influxdb:
    container_name: influxdb
    image: influxdb:latest
    restart: unless-stopped
    ports:
      - '8086:8086'
    volumes:
      - ./docker/data/influxdb:/var/lib/influxdb
    environment:
      # - INFLUXDB_DB=db0
      # - INFLUXDB_ADMIN_USER=admin
      # - INFLUXDB_ADMIN_PASSWORD=admin
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=default
      - DOCKER_INFLUXDB_INIT_PASSWORD=secretsecretsecret
      - DOCKER_INFLUXDB_INIT_ORG=default
      - DOCKER_INFLUXDB_INIT_BUCKET=default
    networks:
      - monitor
  influx-admin:
    container_name: influx-admin
    image: chronograf:latest
    ports:
      - '8888:8888'
    volumes:
      - ./docker/data/chronograf-storage:/var/lib/chronograf
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=default
      - INFLUXDB_PASSWORD=secretsecretsecret
    networks:
      - monitor
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "80:3000"
    restart: always
    networks:
      - monitor
    volumes:
      - ./docker/data/grafana:/var/lib/grafana
    environment:
      # - GF_SERVER_ROOT_URL=http://127.0.0.1
      - GF_AUTH_DISABLE_LOGIN_FORM=false
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false

networks:
  monitor: